spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/order_service_prod?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    jdbc:
      dialect: org.hibernate.dialect.MySQLDialect
